### ISSUE TITLE
メニューエクスポート・インポートのシーケンス番号管理

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/exastro-it-automation#107]
メニューエクスポート・インポートでメニューIDの重複などでユーザ側でシーケンス番号を管理する必要があるため、改善したい。
■改善案
・ITA固有のIDをもって組み合わせる(UUIDの仕組み)
・タグ情報をつける（商用・開発など、どんなレコードか示す）

**Comment by ta-matsuo** [comment]
ITA2.xからは、すべてのメニューで一意キーはUUIDで付与されるようになった。
