### ISSUE TITLE
代入値管理で変数の具体値が登録されていない場合でもMovement実行したい

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/exastro-it-automation#109]
【内容】代入値管理で変数の具体値が登録されていない場合でもMovement実行はできた方がよい
【詳細】
現状だと「Playbookで使用している変数の具体値が代入値管理に登録されていません」と表示されて想定外エラーになるが、下記の場合に邪魔だと感じることもある。
1)　変数が 定義済みか否か(defined と undefined) で処理を分岐させたいとき
2) Roleのdefaults/main.yaml に値が書いてあり、場合によってはそちらを採用したいとき。
3) フィルターを用いて変数のデフォルト値を設定しており、場合によってはそちらを採用したいとき。
 {{ VAR_message | default("hoge" )}}

**Comment by sinatommy** [comment]
1~3のどれも、ITAでnull連携を設定しておいて、値が空文字列の場合に処理を変化させるPlaybookにすれば解決する。
ただ、やはりplaybookをITA仕様にする必要があり、変数が未定義だと動かないというのはAnsible的ではないと思う。

**Comment by sinatommy** [comment]
逆に設定しないといけない値がなしでも動いてしまうのでミスが増える気がする気もしつつ、値入れてほしい場合は入力必須にすればいいとも思える。
入力必須ではない＝具体値不要でも動いてほしいという考え方にするなど。

**Comment by enoman** [comment]
Legacyは、代入値管理で変数の具体値が登録されていない場合でもMovement実行出来るようにする。
Role/Pioneerはこれまで通り。
