### ISSUE TITLE
簡単にgather_factsを有効化できるようにして欲しい

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/exastro-it-automation#111]
【概要】簡単にgather_factsを有効化できるようにして欲しい。
【詳細】
v1.x系ではヘッダーセクション全体を「Movement一覧」に記入する必要があった。
プルダウンで true/falseを変更できるようにするなど、簡単な変更方法があると嬉しい。

**Comment by sinatommy** [comment]
以前は存在したが、廃止した機能。
ヘッダーセクションが多いためフリーフォーマットにした経緯がある。

現在の方式に初期値を入れる？

**Comment by ta-matsuo** [comment]
ITA2.xでは、「Movement一覧」の登録時に「ヘッダセクション」に初期値を入れるように変更してgather_factsの設定を容易に変更できるように改善した。

![image](https://github.com/exastro-suite/exastro-it-automation/assets/49501825/692f2300-b0bd-4354-8613-3495e772ac77)
