### ISSUE TITLE
WinRMの認証方法の多様化

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/exastro-it-automation#113]
【内容】WinRMの認証方法の多様化
【詳細】
現状はWinRMを利用する場合の認証方法が「パスワード認証」一択しかない。証明書での認証を追加した方が、windows serverの管理者には喜ばれると思う。

**Comment by t-uekawa-n** [comment]
httpでのパスワード認証は確認済
httpsでの証明書認証が確認済
httpsでのパスワード認証が未確認
httpでの証明書認証が未確認
