### ISSUE TITLE
【全般】業務エラー系のERRORレベルでのログ出力の精査、制御対応について

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#1207]
ユーザー操作起因による処理のログ出力、業務エラー系のERRORレベルでのログ出力の精査、制御対応

**Comment by ta-matsuo** [comment]
ユーザー操作起因による処理はERRORレベルからINFOまたはDEBUGに変更する。
INFO・・・問い合わせや調査時に解析に必要な情報を出力している場合。
DEBUG・・・それ以外

**Comment by ta-matsuo** [comment]
外部システム（Terraform、AAC、GitHubなど）と通信を行っている箇所は、STARTとENDでINFOレベルでログを出力する。
GitHubについては、Push時に出力。Pull等は出力しない。
