### ISSUE TITLE
【管理コンソール】オペレーション削除管理に論理削除日と物理削除日が論理削除日＜物理削除日に設定されていない場合は該当メニューに対して、論理/物理の削除を行わない。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#1224]
機能：オペレーション削除管理
オペレーション削除管理に論理削除日と物理削除日が論理削除日＜物理削除日に設定されていないと、該当メニューに対して、論理、物理の各削除を行わない。

**Comment by ta-matsuo** [comment]
論理削除日＞物理削除日となっていたとしても、物理削除を行うように変更する。
