### ISSUE TITLE
【Ansible】複数具体値変数を使用した場合、 変数{{ item }}が代入値自動登録設定の「Movement名：変数名」に表示される。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#1262]
Playbookでwith_itemsを使用したときの、
変数{{ item }}が代入値自動登録設定の「Movement名：変数名」に表示されてしまう。
※「item.0」等は表示されない。

**Comment by enoman** [comment]
管理対象外変数一覧にitemを追加
