### ISSUE TITLE
【メニュー作成】項目追加を連打していたら同じ名前で追加された

### ISSUE THREAD

**Issue by T-Sakaki777** [exastro-suite/exastro-it-automation#1354]
項目231までは普通に登録できましたが200あたりから重くなり、もしかしたら連打していたせいかもしれませんが
233から同じ項目名が２つ以上存在しています。（連打は2～3回しました。）
200からは50項目毎に保存を繰り返しており、300までは正常に保存できましたが300以降からこの問題が発生しています。
![重複登録](https://github.com/exastro-suite/exastro-it-automation/assets/121419912/c3c68ef0-d8c0-444c-965d-fba42acbdd1d)

**Comment by HibikiNanri** [comment]
パラメータシート作成実行時の対応として以下を追加する
①「パラメータシート定義・作成」にて「作成」「初期化」「編集」を実行した際、応答が返るまでこれらのボタンを非アクティブ化する
②パラメータシート作成のRESTAPI多重で実行された際にレコードが重複登録されないように修正
