### ISSUE TITLE
【全般】workspace削除時に504 Gateway Timeoutが発生する

### ISSUE THREAD

**Issue by suzuko-f** [exastro-suite/exastro-it-automation#1431]
ita-api-adminで504が出ることがある。PF側にworkspaceが残っているように見えるがアクセスを試みるとエラーになり、時間をおいて再度削除を実施すると消えるという事象が発生している。

**Comment by ta-matsuo** [comment]
Apacheのタイマが未設定（デフォルト60）だったので、300で設定する。

**Comment by ta-matsuo** [comment]
・Workspace削除に時間が掛かるのを防ぐために、Workspace用DBを削除する前にWorkspace用DBに接続しているセッションをすべて切断する処理をいれる。
・バックヤード処理で呼んでいるモジュールがDBをロックしている可能性があるため、モジュール呼出し後に開放する処理を追加する。
