### ISSUE TITLE
【全般】「オペレーション削除」でオペレーション一覧が削除された場合、パラシ（入力用）のオペレーション名が空白となる。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#1435]
「オペレーション削除」でオペレーション一覧が削除された場合、パラシ（入力用）のオペレーション名が空白表示され「ID変換失敗」にならない。　（「編集」で選択するとID変換失敗にはなります。）

**Comment by y-yonekura** [comment]
対応内容
・一覧のオペレーション名(operation_name_disp)の設定変更
	SingleTextColumn→IDColumnに変更
・パラメータシートの作成(編集、初期化)の対応追加
	- 編集時にVIEWの置き換え処理追加

対応後の一覧のオペレーション名（廃止、削除された）の表示について
・2.2で作成されたパラメータシートはID変換失敗(XXXX)表示となる
・2.2以前に作成されたパラメータシートは、2.2でパラメータシート編集/初期化 実施後、ID変換失敗(XXXX)表示となる
