### ISSUE TITLE
【メニュー作成】整数カラムで作成したパラメータシートのフィルター検索を行うと「システムエラー」となる。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#181]
【手順】
①整数カラムのパラメータシートを作成する。
②レコードを1件登録する。
③フィルター検索でfrom,toの両方に値を入れて検索する。
　⇒システムエラーとなる。

**Comment by HibikiNanri** [comment]
フィルター入力欄に0を入れるとシステムエラーになる不具合を対応。
