### ISSUE TITLE
【質問】Ansible Runner 連携

### ISSUE THREAD

**Issue by takeo-e** [exastro-suite/exastro-it-automation#1815]
## 質問内容
Ansible Runner に対応予定はありますか？

**Comment by t-uekawa-n** [comment]
実行エージェントに採用できるか検討。

認証方式を「鍵認証（パスフレーズあり）」の場合、対応予定なし。

**Comment by t-uekawa-n** [comment]
鍵認証（パスフレーズあり）も、イベントリーファイルにパスフレーズを登録すれば、対応可能だったので
実行エージェントに採用。
