### ISSUE TITLE
【OASE】正規表現によるラベル値の置き換えがしたい

### ISSUE THREAD

**Issue by kazuya-domon** [exastro-suite/exastro-it-automation#1875]
### 背景
・正規表現による絞り込みを行いたい
・絞り込まれた値がラベル値として入るようにしたい

### 対応方針
OASEでラベル付与をする際検索条件を正規表現にした際に「ラベル/値」項目をその正規表現によって絞り込まれた値が入るようにしたい。

※
正規表現条件のラベル付与で以下効いていないように見える。
2.4検討事項の対象？（Pythonのオプション使用検討の対象）

メールアドレス　　	[\w.\-]+@[\w\-]+\.[\w.\-]+
行末の。　　。$
空白行	　　　^\n
行全体	　　　^.*$

**Comment by t-uekawa-n** [comment]
ラベル付与設定で、正規表現による検索を行い、ラベルの値を空にした場合、正規表現の検索値、つまり「比較する値」がそのままついてしまうので、正規表現にマッチした値がつくようにしたい

**Comment by t-uekawa-n** [comment]
考慮事項
メールは、メーラーの仕様で自動的に改行が入るケースがある
→正規表現オプションによる検索のしやすさ
→具体的な検索文字列の途中で改行が入るケースについては、切り捨てるしかないのでは？

**Comment by t-uekawa-n** [comment]
OASE管理→エージェント
TTLに設定できる下限値を10にしたい（10秒）

**Comment by t-uekawa-n** [comment]
タスク１：
■ラベル付与
１．検索条件のキー、入力できる文字列の範囲を拡大。・・・説明も修正
２．ラベルの値、正規表現の入力チェックを外す。・・・説明も修正
３．比較方法マスタの値で、正規表現オプションを追加
（全てmigrationを考慮）

**Comment by t-uekawa-n** [comment]
ラベルの値に性表現のキャプチャグループを指定可能。
\1
代替
\g<1>
