### ISSUE TITLE
【Ansible】Ansible-LegayRoleのMovement一覧の項目名不備

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#190]
Ansible-LegayRoleのMovement一覧画面にて、MovementIDのMが全角の大文字になっている。
その隣のMovement名は半角大文字です。
　⇒半角大文字が望ましい。（1系は全て半角大文字となっている）
※英語環境でも同様

**Comment by ta-matsuo** [comment]
#217  でマージ済み。
