### ISSUE TITLE
【Ansible】代入値自動登録設定の登録不備

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#192]
代入値自動登録設定で、IaC変数(To)において、
同一Movementに、Movement名：変数名、代入順序が重複してレコード登録できてしまう。
この状態でansible実行すると、
「The substitution order of variables registered in the substitution value list is duplicated. (substitution value list Item No.:7ffcc27b-9768-49eb-b2b0-5d79d854fc14/6503cea8-a3e4-4dbf-9115-514453c431d2 Variable:VAR_test1 Substitution order:1)」
とエラーになる。

**Comment by sinatommy** [comment]
下記ssueと同件
https://github.com/exastro-suite/exastro-it-automation/issues/232
