### ISSUE TITLE
項目名を利用するプルダウン項目の修正

### ISSUE THREAD

**Issue by y-yonekura** [exastro-suite/exastro-it-automation#2003]
別カラムグループで、同一カラム名の場合に、入力等で不備が出る。

各ドライバ
　代入値自動登録設定のプルダウン
収集
　収集項目値管理のプルダウン
比較
　比較設定詳細のプルダウン
　比較実行時の表示

**Comment by HibikiNanri** [comment]
パラメータシート作成機能の項目を「プルダウン選択」で作る際の「選択項目」も同様の事象であるため修正対象。
