### ISSUE TITLE
メニューインポートのファイルを削除とワークスペースの削除タイミングによってワークスペース削除が失敗する。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#2007]
・メニューインポートでファイルを削除⇒作成
・ワークスペース削除でファイルを削除
がかぶったときに問題が発生する。

**Comment by ta-matsuo** [comment]
タイミングによって以下のエラーが発生する場合がある。
FileNotFoundErrorが発生した場合はエラーにせずに再度削除処理を行うように修正する。

[YYYY-MM-DD hh:mm:ss,nnn][ERROR] [ORGANIZATION_ID:XXX][USER_ID:XXX] [ts=YYYY-MM-DDThh:mm:ss.nnnZ][error]
0 : exception block
 -> "/exastro/controllers/workspace_create_controller.py", line 343, in workspace_delete, shutil.rmtree(workspace_dir)
 -> "/usr/lib64/python3.9/shutil.py", line 734, in rmtree, _rmtree_safe_fd(fd, path, onerror)
 -> "/usr/lib64/python3.9/shutil.py", line 667, in _rmtree_safe_fd, _rmtree_safe_fd(dirfd, fullname, onerror)
 -> "/usr/lib64/python3.9/shutil.py", line 667, in _rmtree_safe_fd, _rmtree_safe_fd(dirfd, fullname, onerror)
 -> "/usr/lib64/python3.9/shutil.py", line 667, in _rmtree_safe_fd, _rmtree_safe_fd(dirfd, fullname, onerror)
 [Previous line repeated 2 more times]
 -> "/usr/lib64/python3.9/shutil.py", line 690, in _rmtree_safe_fd, onerror(os.unlink, fullname, sys.exc_info())
 -> "/usr/lib64/python3.9/shutil.py", line 688, in _rmtree_safe_fd, os.unlink(entry.name, dir_fd=topfd)
 FileNotFoundError: [Errno 2] No such file or directory: 'subst_value_auto_reg_setting_ansible_role'
