### ISSUE TITLE
【メニューインポート】時間指定のインポートが失敗する場合がある。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#2020]

**Comment by HibikiNanri** [comment]
インポート時、ファイルアップロードカラムのファイル格納先に作成するシンボリックリンクが存在していると失敗していまう状態。
（メニューグループ管理のアイコンファイルのようなインストール時に格納されているファイルがある場合に起きるケースがある）

シンボリックリンクが既にある場合は、削除してから作成するよう修正。
