### ISSUE TITLE
【API】バックヤード状態取得APIの返却値についての見直し

### ISSUE THREAD

**Issue by h-nanri** [exastro-suite/exastro-it-automation#2069]
バックヤード状態取得APIの返却値について、現状以下のように「execute_countと[organization-name]」「execute_countと[workspace-name]が同階層にあるため、「execute_count」という名前のorganizationやworkspaceを作成すると返却値が崩れる。

対処案
①「_execute_count」と予約語を使う
②同階層にならないよう構成を見直す

```
{
  "data": {
    "execute_count": 0,
    "organization-name": {
      "execute_count": 0,
      "workspace-name": {
        "execute_count": 0,
        "ita-by-ansible-execute": [],
        "ita-by-conductor-synchronize": [],
        "ita-by-excel-export-import": [],
        "ita-by-menu-create": [],
        "ita-by-menu-export-import": []
      }
    }
}
```

**Comment by ta-matsuo** [comment]
以下のように構成を変更。

`
{
  "result": "000-00000",
  "data": {
    "execute_count": 0,
    "organizations": [
      {
        "id": "(organiation_id)",
        "execute_count": 0,
        "workspaces": [
          {
            "id": "(workspace_id)",
            "execute_count": 0,
            "backyards": {
              "(backyard_container_name)": [
                {
                  "id": "(uuid)",
                  "status_id": "1",
                  "status_name": "未実行",
                  "last_update_timestamp": "YYYY-MM-DD hh:mm:ss.xxxxxx"
                }
              ]
            }
          }
        ]
      }
    ]
  },
  "message": "string"
}
`
