### ISSUE TITLE
【OASE】監視ツールのAPIからのイベント取得

### ISSUE THREAD

**Issue by kazuya-domon** [exastro-suite/exastro-it-automation#2093]
### 背景
現状エージェントがイベントを取得してきているが、監視ツールからAPIでイベントが登録できるようにしたい

### 対応方針
APIによる登録が可能になるようにする。

**Comment by koujiSunakawa** [comment]
# 1. 「認証方式テーブル設計」シートのリレーション 
## 1.1. 「認証方式テーブル設計」シートのER図

```mermaid
erDiagram

    AUTHENTICATION_METHOD ||--o{ AUTHHENTICATION_INFOMATION : authhentication_method_id
    AUTHHENTICATION_INFOMATION {
        varchar authhentication_infomation_id PK "認証情報ID"
        varchar authhentication_method_id FK "認証方式ID"
        varchar token "案①　トークン"
        varchar user_id "案①　ユーザーID"
        varchar password "案①　パスワード"
        varchar host_name "案①　ホスト名"
        int     port "案①　ポート"
        varchar communication_method "案①　通信方式"
        varchar access_key_id "案①　アクセスキーID　？"
        varchar secret_access_key "案①　秘匿アクセスキー　？"

        varchar authentication_information "案②　認証方式情報(JSON)"
    }

    AUTHENTICATION_METHOD {
        varchar authhentication_method_id PK "認証方式ID"
        varchar authentication_method_name "認証方式名"
    }

    AUTHHENTICATION_INFOMATION ||--o{ GATHERING_EVENT_AUTHENTICATION_INFOMATION : authhentication_infomation_id
    GATHERING_EVENT ||--o{ GATHERING_EVENT_AUTHENTICATION_INFOMATION : GATHERING_event_id
    GATHERING_EVENT_AUTHENTICATION_INFOMATION {
        varchar GATHERING_event_id PK "イベント収集の設定ID"
        varchar authhentication_infomation_id PK "認証情報ID"
    }

    MONITORING_TOOL {
        varchar monitoring_tool_id  PK "監視ツールID"
        varchar monitoring_tool_name "監視ツール名"
    }

    MONITORING_TOOL ||--o{ GATHERING_EVENT : monitoring_id

   GATHERING_EVENT {
        varchar GATHERING_event_id PK "イベント収集の設定ID"
        varchar GATHERING_event_name "イベント収集の設定名"
        varchar monitoring_tool_id FK "監視ツールID"
        varchar api_url "API URL"
        boolean is_list "リスト有無　？"
        varchar list_key "リストキー　？"
        varchar parameter "パラメータ　？"
    }    

```

**Comment by koujiSunakawa** [comment]
## 1.3. 監視ツールの「認証情報」と「イベント収集の設定」の関係(見直し案)
---
- **「監視ツール」と「認証情報」、「イベント収集の設定」の関係**
    - 「認証情報」と、「イベント収集の設定」のリレーションは、なし
    - 「監視ツール」と、「認証情報」のリレーションは、**「1：1」**
    - 「監視ツール」と、「イベント収集の設定」のリレーションは、**「1：n」**
```mermaid
    graph TD

    Zabbix_v6.0[監視ツール<br>Zabbix_ver6.0]
    alert[イベント収集の設定<br>Alert]
    problem[イベント収集の設定<br>Broblem]
    trigge[イベント収集の設定<br>Trigge]

    Zabbix_v6.0 -- イベント収集の設定<br>1:n --> alert
    Zabbix_v6.0 -- イベント収集の設定<br>1:n --> problem
    Zabbix_v6.0 -- イベント収集の設定<br>1:n --> trigge
    Zabbix_v6.0 -- 認証情報<br>1:1 --> 認証情報_1
```
---
- **複数の同一「監視ツール」で、「認証情報」、「イベント収集の設定」の関係**
    - 「監視ツール」と、「イベント収集の設定】を、【監視ツール_イベント収集の設定】テーブルでリレーションを付けることで対応
    - 同一「監視ツール」で、異なる「バージョン」でも、同じ「認証情報」、「イベント収集の設定」を指定できる。
```mermaid
    graph TD

    Zabbix_v6.0[監視ツール<br>Zabbix_v6.0]
    auth_info_1[認証情報_1]
    alert[イベント収集の設定<br>Alert]
    problem[イベント収集の設定<br>Broblem]
    trigge[イベント収集の設定<br>Trigge]

    Zabbix_v6.4[監視ツール<br>Zabbix_v6.4]
    alert_v6.4[イベント収集の設定<br>Alert V6/4]
%%    problem_v6.4[イベント収集の設定<br>Broblem V6/4]
    trigge_v6.4[イベント収集の設定<br>Trigge V6/4]


    Zabbix_v6.0 -- イベント収集の設定<br>1:n --> alert
    Zabbix_v6.0 -- イベント収集の設定<br>1:n --> problem
    Zabbix_v6.0 -- イベント収集の設定<br>1:n --> trigge
    Zabbix_v6.0 -- 認証情報<br>1:1 --> auth_info_1

    Zabbix_v6.4 -- 認証情報<br>1:1 --> auth_info_1
    Zabbix_v6.4 -- イベント収集の設定<br>1:n --> alert_v6.4
    Zabbix_v6.4 -- イベント収集の設定<br>1:n --> problem
    Zabbix_v6.4 -- イベント収集の設定<br>1:n --> trigge_v6.4


```
---
- **異なる「監視ツール」間では、同一「認証情報」は指定不可とする**
    - 【監視ツール】と、「イベント収集の設定】で、「監視ツールID」を定義することで対応
```mermaid
    graph TD

    Zabbix_v6.0[監視ツール<br>Zabbix_ver6.0]
    

    Zabbix_v6.0 --  認証情報<br>OK --> 認証情報_1
    Gradana --  認証情報<br>NG --> 認証情報_1
```

**Comment by koujiSunakawa** [comment]
# 2. API呼び出しをテンプレート化（案）
```mermaid
    graph LR
    monitoring_tool[監視ツールの<br>APIが]
    template_pg[テンプレートを利用した<br>プログラム]
    individual_pg[個別対応プログラム]

    monitoring_tool -- テンプレート<br>で対応可能 --> template_pg
    monitoring_tool -- 複雑な *1 <br>API呼び出し --> individual_pg
```
- *1
    - 複数回のAPI呼び出しを、行わなければならない場合
    - APIのレスポンスｌを、特別な処理を行う必要がある場合

---
## 2.1. 【AUTHHENTICATION_INFOMATION】認証方式情報の設定内容について
- **Zabbixの認証API**
    - **curlコマンド**
        ```
        curl --request POST \
            --url 'https://example.com/zabbix/api_jsonrpc.php' \
            --header 'Content-Type: application/json-rpc' \
            --header 'user-agent: vscode-restclient' \
            --data '{"jsonrpc":"2.0","method":"user.login","params":{"username":"Admin","password":"zabbix"},"id":1}'

        {"jsonrpc":"2.0","result":"f2f43bfc9bdc98d876a855b1701f4faa","id":1}
        ```
    - **テンプレート例**
        ```
        {
            [
                "request": {
                    "method": "POST",
                    "url": "{{ auth_api_url }}",
                    "header": [
                        "Content-Type: application/json-rpc",
                        "user-agent: vscode-restclient"
                    ],
                    "data": "{\"jsonrpc\":\"2.0\",\"method\":\"user.login\",\"params\":{\"username\":\"{{ user_id }}\",\"password\":\"{{ password }}\"},\"id\": {{ access_serial_number }} }"
                                └─API呼び出し毎に、カウントアップする値に置換
                },
                respons: { 
                    "access_key_id": { 
                        "regexp" : "\"result\":[\s]*\"([0-9a-z]+)\""
                        　　└─ (「イベント取得」で利用するアクセスキーを取得する正規表現で、
                        　　　　取得した値を「監視ツール情報マップ」の値として格納)
                    }
                }
            ]
        }
        ```
    - テンプレートを使用しない場合
        - 条件
            - 【認証情報】認証方式情報 が、空文字、またはNull場合
        - 処理するモジュールを、下記の条件で特定、
            - 【監視ツール】監視ツール名
            - 【監視ツール】バージョン
        - 特定できたモジュールの、認証処理(関数)を呼び出す。
        - 処理するモジュールが特定できない場合、処理を行わない。
---
## 2.2. **【イベント収集の設定】パラメータのテンプレート例**

- **Zabbix Problemイベント取得API**

    - **curlコマンド**
        ```
        curl --request POST \
            --url http://localhost:7780/api_jsonrpc.php \
            --header 'content-type: application/json-rpc' \
            --header 'user-agent: vscode-restclient' \
            --data '{"jsonrpc": "2.0","method": "problem.get","id": 1,"params": {},"auth": "d1d878f8c7578a0d2c0b213bdf7b7f72"}'

        {
            "jsonrpc": "2.0",
            "result": [
                {
                "eventid": "75",
                "source": "0",
                "object": "0",
                "objectid": "22384",
                "clock": "1689839844",
                "ns": "61203573",
                "r_eventid": "0",
                "r_clock": "0",
                "r_ns": "0",
                "correlationid": "0",
                "userid": "0",
                "name": "Linux: High CPU utilization (over 90% for 1m)",
                "acknowledged": "0",
                "severity": "2",
                "opdata": "Current utilization: 98.8598 %",
                "suppressed": "0",
                "urls": []
                }
            ],
            "id": 2
        }
        ```
    - **テンプレート例**
        ```
        {
            [
                "request": {
                    "method": "POST",
                    "url": "{{ event_api_url }}",
                    "header": [
                        "content-type: application/json-rpc",
                        "user-agent: vscode-restclient"
                    ],
                    "data": "{\"jsonrpc\": \"2.0\",\"method\": \"problem.get\",\"id\": {{ access_serial_number }},\"params\": {},\"auth\":\"{{ access_key_id }}\" }"
                },
                "respons": {} ←(設定がない場合、レスポンスの全てをDBに格納)
                }
            ]
        ```
    - テンプレートを使用しない場合
        - 条件
            - 【イベント収集の設定】パラメータ が、空文字、またはNull場合
        - 処理するモジュールを、下記の条件で特定、
            - 【監視ツール】監視ツール名
            - 【監視ツール】バージョン
        - 特定できたモジュールの、イベント取得処理(関数)を呼び出す。
        - 処理するモジュールが特定できない場合、処理を行わない。

**Comment by koujiSunakawa** [comment]
# 3. 「監視ツールイベント収集処理」プログラム構成(案)

## 3.1. 処理概要
```mermaid
    graph TD

    auth_db_fetch["有効な<br>処理対象の【監視ツール・バージョン】をDBから取得"]
    event_db_fetch["「監視ツール」や「バージョン」で、<br>【イベント収集の設定】をDBから取得"]
    auth["認証RESET-APIを呼び出し<br>認証処理"]

     エージェント --> 監視ツールイベント収集処理

    subgraph 監視ツールイベント収集処理

        auth_db_fetch --"読込んだ結果を、<br>「認証情報(配列)」として渡す"--> 監視ツールバージョンの繰り返し

        subgraph 監視ツールバージョンの繰り返し
            
            イベント収集の設定の繰り返し --"次「監視ツールバージョン」"--> auth
            auth --> event_db_fetch
            
            event_db_fetch -- "access_key_idと、<br>【イベント収集の設定】<br>を渡す " --> イベント収集の設定の繰り返し
            subgraph イベント収集の設定の繰り返し
                mongoDB/maridDB格納 --"次「イベント収集の設定」"--> イベント収集処理
                イベント収集処理 -- "レスポンスから取得した値、<br>または、レスポンス全体" --> mongoDB/maridDB格納
            end 
        end

        
    end

    監視ツールイベント収集処理 --"結果(True/False) ←(不要？)"--> エージェントの後処理
```
---
## 3.2. 処理詳細
- 「エージェント」が、、「監視ツールイベント収集処理」(以下、「本処理」)を、引数なしで、起動する。
- 本処理で、（DBに登録された、全「監視ツール・バージョン」、全「イベント収集の設定」を処理する）
    1. 有効な処理対象の【監視ツール・バージョン】をDBから取得
    1. 取得した【監視ツール・バージョン】の要素（以下、「認証情報」）分以下を繰り返す。
        1. 「APIリクエスト」を作成
            -下記の条件でを作成
            - 置換対象
                - 「認証情報」の、APIテンプレー項目
            - 被置換対象
                - 【監視ツール・バージョン】の列名(lowecase)に合致する項目を、値で置換する。
        1. 「APIリクエスト」で、認証APIを呼び出す。
        1. 認証APIのレスポンスから、「アクセスキー」を取得する。
        1. 「監視ツール」や「バージョン」で、【イベント収集の設定】をDBから取得
        1. 取得した【イベント収集の設定】の要素数分、以下を繰り返す。
            1. 「APIリクエスト」を作成
                -下記の条件で、「APIリクエスト」を作成
                - 置換対象
                    - 【イベント収集の設定】のAPIテンプレート
                - 被置換対象
                    - 【イベント収集の設定】の列名(lowecase)に合致する項目を、値で置換する。
                    - "access?key_id"に合致する項目を、「アクセスキー」で置換する。
            1. 「APIリクエスト」で、イベント収集APIを呼び出す。
            1. イベント収集APIのレスポンスから、DBに格納する値を取得する。
                - 特定の値を取得する場合、取得した値を対象
                - 値を取得しない場合は、レスポンス全体が対象
            1. mondoDB,MariaDBに必要な値を格納する。
- 本処理終了後、「エージェント」に結果（True/False）を返却する。


## 3.3. エラー発生時の対処
- 「監視ツール・イベント収集処理」
    - 「監視ツール・バージョン】読込失敗(DBエラー)
        - 処置
            1. エラーログ出力
            1. 本処理呼出元へ、結果を、失敗(False)で返却して
            1. 「監視ツール・イベント収集処理」を抜ける（終了）
- 「監視ツール・イベント収集処理」
    - 認証情報の不正(必須項目未設定)
        - 処置
            1. エラーログ出力
            1. 次「 監視ツール・イベント」を処理
    -  認証失敗
        - 監視サーバー不到達
        - リクエスト形式不正)
        - 処置
            1. エラーログ出力
            1. 次「 監視ツール・イベント」を処理
    - アクセスキー取得失敗
        - 【認証上納】の被取得情報の不正
        - レスポンスに取得対象項目なし)
        - 処置
            1. エラーログ出力
            1. 次「 監視ツール・イベント」を処理
- 「イベント収集の設定の繰り返し」
    - イベント取得失敗
        - サーバー不到達
        - リクエスト形式不正
        - 処理
            1. エラーログ出力
            1. 次「イベント収集の設定」を処理
    - mongoDB、mariaDB格納失敗(DBエラー)
        - 処置
            1. DBロールバック
            1. エラーログ出力
            1. 本処理呼出元へ、結果を、失敗(False)で返却して
            1. 「監視ツール・イベント収集処理」を抜ける（終了）

**Comment by koujiSunakawa** [comment]
# 「接続方式」毎の入力必須チェック
- "－"：入力不要（入力しても利用されない）  
- "〇"：入力可（使用される項目で、未入力でもOK）
- "◎"：必須（未入力時エラー）  

| 列名 | Bearer認証 | パスワード認証 | SharedKeyLite認証 | IMAP パスワード認証 | 任意の認証考 | 備考 |
|------|-----------|---------------|-------------------|--------------------|--------------|--|
| リクエストメソッド | ◎GET/POST | ◎GET/POST | ◎GET/POST | ◎ | ◎POST | |
| 接続先 | ◎ | ◎ | ◎ | ◎ | ◎ | |
| リクエストヘッダー | 〇 | 〇 | 〇 | － | 〇 | *1 |
| 認証トークン | ◎ | － | － | － | － | |
|ユーザー名 | － | ◎ | － | ◎ | － | |
| パスワード | － | ◎ | － | ◎ | － | |
| メールボックス名 | － | － | － | 〇 | － | |
| アクセスキーID | － | － | ◎ | － | － | |
| 秘密アクセスキー | － | － | ◎ | － | － | |
| パラメータ | － | － | － | － | ◎ | |

- 1： Bearer認証、パスワード認証、SharedKeyLite認証で、「リクエストヘッダー」に、"Authorization:"の記述は不要

**Comment by koujiSunakawa** [comment]
# エージェントの入力例

## Bearer認証
- 「エージェント」での入力内容  
    1. リクエストメソッド（&lt;REQUEST_METHOD&gt;）**【必須】**  
        - 値： GET または、POST
    1. 接続先（&lt;URL&gt;）**【必須】**  
        - 値："?"後のパラメータを含まない値  
        - 入力例： 'http://･･･････' または'https://･･･････'
    1. リクエストヘッダー（&lt;REQUEST_HEADER&gt;）**【省略可】**  
        - 値： 「Authorizationヘッダー」以外のヘッダー情報
        - 入力例：Grafanaの場合  
            ```
            "Content-Type": "application/json"
            ```
    1. 認証トークン（&lt;AUTH_TOKEN&gt;）**【必須】**  
        - 値： 監視ツールで生成した、Bearer認証のトークン
    1. パラメーター（&lt;PARAMETER&gt;）**【省略可】**  
        - 　値：　接続先の"?"以降の値を入力、なければ省略  
- リクエスト形式
    ```
    --request <REQUEST_METHOD>
    --url <URL>?<PARAMETER> ←･･･"GET"の場合、"?<PARAMETER>"を追加
    --header Authorization: Bearer <AUTH_TOKEN>
    --header <REQUEST_HEADER> ←･･･「エージェント」画面で入力があれば追加
    --data <PARAMETER> ←･･･"POST"の場合、追加
    ```

## Basic認証
- 「エージェント」での入力内容
    1. リクエストメソッド（&lt;REQUEST_METHOD&gt;）**【必須】**  
        - 値： GET または、POST
    1. 接続先（&lt;URL&gt;）**【必須】**  
        - 入力例： 'http://･･･････' または'https://･･･････'
    1. リクエストヘッダー（&lt;REQUEST_HEADER&gt;）**【省略可】**  
        - 値： 「Authorizationヘッダー」以外のヘッダー情報
        - 入力例：  
            ```
            "Content-Type": "application/json"
            ```
    1. ユーザー名（&lt;USERNAME&gt;）**【必須】**  
    1. パスワード（&lt;PASSWORD&gt;）**【必須】**  
    1. パラメーター（&lt;PARAMETER&gt;）**【省略可】**  
        - 　値：　接続先の"?"以降の値を入力、なければ省略  
- リクエスト形式
    ```
    --request <REQUEST_METHOD>
    --url <URL>?<PARAMETER> ←･･･"GET"の場合、"?<PARAMETER>"を追加
    --header Authorization: Basic <USERNAME>:<PASSWORD>
    --header <REQUEST_HEADER> ←･･･「エージェント」画面で入力があれば追加
    --data <PARAMETER> ←･･･"POST"の場合、追加
    ```

## SharedKeyLite認証
- 「エージェント」での入力内容
    1. リクエストメソッド（&lt;REQUEST_METHOD&gt;）**【必須】**    
        - 値： GET または、POST
    1. 接続先（&lt;URL&gt;）**【必須】**  
        - 入力例： 'http://･･･････' または'https://･･･････'
    1. リクエストヘッダー（&lt;REQUEST_HEADER&gt;）**【省略可】**  
        - 値： 「Authorizationヘッダー」以外のヘッダー情報
        - 入力例： Azureの場合、
            ```
            "x-ms-version": "<APIのバージョン>"
            ```
    1. アクセスキーID（&lt;ACCESS_KEY_ID&gt;）**【必須】**  
      - 値： 監視ツールで生成した、アクセスキーID
    1. 秘密アクセスキー（;SECRET_ACCESS_KEY&gt;）**【必須】**  
      - 値： 監視ツールで生成した。秘密アクセスキー
    1. パラメーター（&lt;PARAMETER&gt;）**【省略可】**  
        - 　値：　接続先の"?"以降の値を入力、なければ省略  
        - 入力例：   
            ```
            includeContext=True&api-version=2019-03-01'
            ```
- リクエスト形式
    ```
    --request <REQUEST_METHOD>
    --url <URL>?<PARAMETER> ←･･･"GET"の場合、"?<PARAMETER>"を追加
    --header Authorization:"SharedKeyLite <access_key_id>: <secret_access_key>
    --header Date: <agent側でリクエスト日時を設定>
    --header <REQUEST_HEADER> ←･･･「エージェント」画面で入力があれば追加
    --data <PARAMETER> ←･･･"POST"の場合、追加
    ```
## 任意の認証
- 「エージェント」での入力内容
    1. リクエストメソッド（&lt;REQUEST_METHOD&gt;）**【必須】**  
        - 値： POST
    1. 接続先（&lt;URL&gt;）**【必須】**  
        - 入力例： 'http://･･･････' または'https://･･･････'
    1. リクエストヘッダー（&lt;REQUEST_HEADER&gt;）**【省略可】**    
        - 値： 「Authorizationヘッダー」以外のヘッダー情報
        - 入力例: Zabbixの場合：
            ```
            "content-type": "application/json-rpc""
            ```
    1. パラメーター（&lt;PARAMETER&gt;）**【省略可】**  
        - 入力例：Zabbixの場合
            ```
            "jsonrpc": "2.0",
            "method": "problem.get",
            "auth": "xxxxxxxxxxxxxxxxx" ･･･Zabbixで作成したアクセスキー
            "id": 1
            ```
- リクエスト形式
    ```
    --request <REQUEST_METHOD>
    --url <URL>
    --header <REQUEST_HEADER> ←･･･「エージェント」画面で入力があれば追加
    --data <PARAMETER>
    ```

**Comment by koujiSunakawa** [comment]
# 2024-03-01 ITA開発の検討会での修正事項  
- OSASE管理＞エージェントで下記の項目を追加  
  - レスポンスリストフラグ
    - DISUSE_FLAG：1→0へ修正
  - レスポンスキー【修正 1→0】  
    - DISUSE_FLAG：1→0へ修正
  - URLパラメータ【追加】
    - GET or POSTで、URLの"?"以降に追加するパラメータ
    - パラーメータの左側・上側に表示
- エージェントでのエラーの扱い  
  - Exceptionで、抜けるパターンの処置追加  
    - 接続できない  
    - 有効期限切れ  
      - HTTP-STATUSが、"401 Unauthorized"を返す  
  - それ以外  
    - レスポンスを返す
- イベント取得範囲の指定
  - パラメータ中に、"EXSASTRO_LAST_FETCHED_TIME"があれば、
  &nbsp;&nbsp;【イベント履歴】イベント収集日時＋1ミリ秒の日時に置換
    - 【イベント履歴】イベント収集日時の取得
        ```
        select
          max(fetched_time) as fetched_time
        from
          T_OASE_EVENT_HISTORY -- イベント履歴
        where
          event_collection_settings_id = <処理するイベント収集設定ID>
        ```

**Comment by koujiSunakawa** [comment]
- OSASE管理＞エージェントで下記の項目を追加  
  - レスポンスリストフラグ  
    - DISUSE_FLAG：1→0へ修正  
  - レスポンスキー  
    - DISUSE_FLAG：1→0へ修正

**Comment by koujiSunakawa** [comment]
# Zabbixのイベント収集結果

1. Zabbixサーバーで、下記のコマンドを投入して、   
　CPU負荷90%台を、５分間超えた状態にする  
  ```
   $ openssl speed -multi `grep processor /proc/cpuinfo|wc -l`
   ```
1. Zabbixの「Problems」で、CPU負荷の表示がでる  
1. ita-ag-oaseコンポーネントで、エージェントを起動  
  ```
  $ python3 ./agent/agent_init.py
  ```
1. イベント収集１回目で、ZabbixのProblemsのイベントを取得
1. イベント取集宇２回目で、イベント取得しない  
　　下記のオプションの影響
　　acknowledged　boolean  
　　　├True - 確認済みの障害を返します  
　　　└false - 未確認の障害を返します･･･省略時  
　　　関連：https://www.zabbix.com/documentation/current/jp/manual/api/reference/problem/get
1. Exsastroの「おベントフロー」に、Zabbixのイベントが表示されている。

**Comment by koujiSunakawa** [comment]
# テストケース  
## バリデーション  
- 必須エラー・パターン  
    - 各認証方式で、必須項目を空で【登録確認】押下  
    - 期待値  
        - バリデーションエラーになること  
        
- JSON形式エラー・パターン  
    - IMAP認証以外で、  
        - リクエストヘッダーで、JSON形式以外で入力  
        - パラーメータで、JSON形式以外で入力  
    - 期待値  
        - バリデーションエラーになること  
        
- 正常登録パターン  
    - 各認証方式で、必須項目を正しく指定し【登録確認】押下  
    - 期待値  
        - バリデーションエラーにならないこと  
        - 登録できること  
        - 【フィルター】押下で、入力した内容が表示されること    

- 正常更新パターン  
    - 各認証方式を、選択後、【編集】押下  
    - 期待値  
        - 登録した内容が表示されること  
    - 名称等を変更し、【登録確認】押下  
    - 期待値  
        - バリデーションエラーにならず  
        - 変更できること  
        - 【フィルター】押下で、入力した内容が表示されること  

## エージェント
- 接続成功パターン
    - イベントなし
        - 期待値
            - イベントフローになにも表示されないこと
    - イベントあり
        - 期待値
            - イベントフローに表示されること
            - ラベル付与が正しく行われること
- 接続失敗パターン
    - 接続先間違い
        - 期待値
            - エラーログにエラーが表示されること
    - 認証情報が不正
        - Bearer認証
            - 認証トークンを正しくない値に設定
            - 期待値
               - エラーログにエラーが表示されること
        - 任意の認証
            - パラメーターの認証情報正しくない値に設定
            - 期待値
               - エラーログにエラーが表示されること
    - 認証有効期限切れ
        - Bearer認証
            - 期限が切れそうな認証トークンを作成
            - 認証トークンに設定
            - 期待値
               - エラーログにエラーが表示されること
        - 任意の認証
            - 新しいAPIキーを作成
            - 古いAPIキーのままで接続
            - 期待値
               - エラーログにエラーが表示されること

**Comment by koujiSunakawa** [comment]
# 環境変数「NO_PROXY」と、エージェント

### 現象
環境変数「NO_PROXY（プロキシ利用しない）」に記載された、アドレスを、
OASE管理＞エージェントの「接続先」に指定した場合、

エージェントで、「接続先」に接続する際に、
requestsの引数で、"verify=False," を指定しないと
プロキシに接続して、正しく接続できない。

### 対応
1. 環境変数「NO_PROXY」を取得
2. OASE管理＞エージェントで登録した「接続先」から「アドレス（ホスト）名」を取得
    - 接続先='http://grafana:3000/api/alerts' の場合
    - 取得値＝'grafana'
3. 環境変数「NO_PROXY」に、「アドレス」が
    - 存在する場合･･･→verify=False
    - 存在しない場合･･･→verify=None
4. requestsの引数verifyを、3.の値で設定

```
            response = requests.request(
                method=<リクエストメソッド>
                url=<接続先>
                   ：
                verify=False,   ･･･この設定を追加
                proxies=proxies
            )
```

**Comment by koujiSunakawa** [comment]
# GrafanaをDockerで起動し、エージェントでイベント収集する手順

## 1. GrafanaをDockerで起動から、「認証トークン」の取得まで
1. VM上に適当なディレクトリに作成
    ```
    $ mkdir ~/grafana）
    ```
1. 作成したディレクトリへ移動
    ```
    $ cd =/grafana）
    ```
1. Grafanaチュートリアルを、クローン
    ```
    $ git clone https://github.com/grafana/tutorial-environment.git
    ```
1. Grafanaチュートリアルを、起動
    ```
    $ docker-compose up -d
    ```
1. ブラウザを開く
1. URLに、`http://localhost:3000`を入力
1. 下記のユーザー名/パスワードでログイン
    - username: admin
    - Password: admin
1. パスワードを変更して、【save】
1. 【Add a metrics data source】をクリック
1. 【Prometheus】をクリック
1. 「URL」に下記を入力
    ```
    http://prometheus:9090
    ```
1. 下へスクロールして、【Save & test】をクリック  
1. Home > Administration > Service accounts を選択  
1. 【service account】をクリック  
1.  サービス名を小文字で入力  
1. 【Add service account token】をクリック  
1.  「Expiration」で、"No expiation"(期限なし）)または、"Set expiation"（期限あり）を選択  
1.  【Generate token】をクリック  
1. 【Copy to clipboard and close】をクリック  
1.  OASE管理＞エージェントの画面の「認証トークン」に張り付け  

## 2. Exsastro環境の設定
下記の手順で、環境変数「NO_PROXY」を設定する。
1. Grafanaチュートリアルの、docker-compose.ymlを表示
    ```
    $ car ~/grafana/tutorial-environment/docker-compose.yml
    ```
1. 表示された、docker-compose.ymlから、ネットワーク名をメモ
    ```
    networks:
        <ネットワーク名>: ･････ここのネットワーク名の値をメモ
    ```
1. 起動するエージェントの環境編(.env)ファイルのあるディレクトリへ移動
    ```
    $ cd /home/azureuser/exastro-suite/
    $ ls -la
	    # agent1からagent8まであることを確認する
    # agent5でテストする場合
    $ cd /home/azureuser/exastro-suite/agent5

    $ vi ./.env
	    # .envのIMG_VERSIONの値を
	    # https://hub.docker.com/r/exastro/exastro-it-automation-ag-oase/tags
	    # の最新の値で書き換える。

        # 環境変数NP?PROXYがあれば、末尾に、上記2.でメモした値を",<ネットワーク名>"で追加
        NO_PROXY=localhost,127.0.0.1,ita-api-organization,ita-api-admin,ita-web-server,platform-api,platform-auth,ita-api-oase-receiver  ････末尾に、",<ネットワーク名>"を追加
        - no_proxy=localhost,127.0.0.1,ita-api-organization,ita-api-admin,ita-web-server,platform-api,platform-auth,ita-api-oase-receiver  ････末尾に、",<ネットワーク名>"を追加
1. 保存

## 3. エージェントの起動
1. 全エージェントを起動
    ```
    $ docker-compose up -d
    ```
1. 接続するエージェントの、サービス名 を探す
```
$ docker ps | grep agent
```
1. エージェントに入る
    ```
    $ docker exec -it <サービス名> bash
    ```
