### ISSUE TITLE
【OASE】無限ループ対策

### ISSUE THREAD

**Issue by kazuya-domon** [exastro-suite/exastro-it-automation#2100]
### 背景
ルールの設定失敗すると無限ループしてしまう。

### 対応方針
下記のような対応が考えられる
・無限ループの際に検知する機能
・ループが設定できないようにする

**Comment by kazuya-domon** [comment]
### 実現案

1. 結論イベントのexatsro_ruleの情報をもとに同一ルールにマッチする場合はエラーを表示したうえでスキップするようにする
2. 結論イベントのexatsro_ruleに経由したルールIDと名前をすべて残しておく（案①強化版）
3. 画面側で結論イベントに既存フィルターに引っかかるラベル設定した場合に警告画面を出す。（案②にプラスする感じ）
4. ルールを作るときに疑似ルールマッチをして、無限ループを検知する。（無限ループ検知用ルールマッチ）

### 懸念

現在イメージしているやり方だと、MongoDBへ保存する結論イベントのデータ構造を変える必要がありそう。
その場合、画面側の表示にも跳ねることが想定されるので、修正作業が結構ある想定

**Comment by kazuya-domon** [comment]
このissueでは前段階として、
イベントのexatsro_rulesを辞書形式から配列＋辞書に変更までとする。

実際にマッチをはじくのは別issue対応

**Comment by t-uekawa-n** [comment]
具体的な修正方針

```
{
"_id":   ObjectId("83jmc4j53gefsjm7gkw4r4uxt")
"labels": {
　"_exastro_event_collection_settings_id": "",
　"_exastro_fetched_time": ”1691384281",
　"_exastro_end_time": "1691384581",
　"_exastro_checked": "0",
　"_exastro_timeout": "0",
　"_exastro_evaluated": "0",
　"_exastro_undetected": "0",
　"_exastro_checked": "0",
　"_exastro_type": "conclusion",
　"CPU   usage": "High"
　"Server": "Down"
　"Host":   "web01",
　"_exastro_rule_name": "Serverdown",
}
"exatsro_rule": {
　id:   "1231d282-d104-4b2b-b8fb-89954504a950”
　name:   "Serverdown"
}
```
のexatsro_rule部分の構造変更。

```
{
"_id":   ObjectId("83jmc4j53gefsjm7gkw4r4uxt")
"labels": {
　"_exastro_event_collection_settings_id": "",
}
"exatsro_rule": [
 {
　id:   "1231d282-d104-4b2b-b8fb-89954504a950”
　name:   "Serverdown"
 }
]
```

サーバ側で配列で挿入。
フロントエンド側では配列のインデックス0で取得（イベントフロー画面での修正想定）
