### ISSUE TITLE
【OASE】事前・事後通知テンプレートにイベント情報、実行内容(アクション、Conductor)を渡せるようにする

### ISSUE THREAD

**Issue by kazuya-domon** [exastro-suite/exastro-it-automation#2103]
### 背景
通知のテンプレートに実行結果などを含ませたい

### 対応方針
下記の情報を通知できるようにしたい。
・イベント情報
・アクション（Conductor）の実行結果

**Comment by takeo-e** [comment]
Conductor 実行失敗した場合にも情報連携できるようにしてほしい。

**Comment by takeo-e** [comment]
具体的な利用ユーザーが想定されるため、優先度を上げてほしい
