### ISSUE TITLE
【OASE】メール本文にバイナリデータが入ると、エージェントがエラーとなる。

### ISSUE THREAD

**Issue by kazuya-domon** [exastro-suite/exastro-it-automation#2106]
### 背景
メール本文にバイナリデータが入ると処理が落ちる。

### 対応方針
取り込み時にエラーが発生してもスキップをして、処理を続けるようにする。

**Comment by t-uekawa-n** [comment]
・メーラーが落ちている場合などのエラーは、取得日時を保存しない。→最終取得した日時から再取得をはじめる
・デコードで失敗するなど、不備データでエラーになる場合は、不備あるのデータとして保存（＆API送信）し、処理を続ける。エラーをINFOとしてログには出すが、処理としては無視する。

**Comment by t-uekawa-n** [comment]
・メッセージIDがなければ、エージェントでつける。ロジックは、設定名_Dateの受信日時
・Dateもないと受信日時の判定が出来ないので、無理やり古い日時（前回の取得日時-1マイクロ秒）を入れて、処理対象（保存やITAの送信対象）から外す

・通知サーバをイベント収集対象サーバにすると、無限ループになる可能性があるので、要注意
