### ISSUE TITLE
「Playbook素材集」等に「Python無しで動くのか、Linux、Windows、その他、のどれで動くものなのか」を管理するカラムを追加してください

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/exastro-it-automation#2116]
Playbook素材、対話ファイル素材、ロールパッケージ管理、をターゲットに話します。
まず、該当のIaCが「ターゲットホストにPythonがインストールされていることを期待するのか、無くても動くのか？」を管理するカラムを付けて下さい。(〇×のフラグでOKです。)
そして、それとは別に、
該当のIaCがLinuxで動作するのか(〇×)、Windowsで動作するのか(〇×)、その他(その他は文字列で記載できるように)のカラムを搭載してください。
「その他」にはAWSやAzureやGCPやVMwareが記載されるイメージです。

以上。

**Comment by ta-matsuo** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///D:/Users/000001~1.000/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///D:/Users/000001~1.000/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>


ターゲット | Python要否
-- | --
Linux | Windows | その他



</body>

</html>

**Comment by ta-matsuo** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///D:/Users/000001~1.000/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///D:/Users/000001~1.000/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>


ターゲット | Python要否
-- | --
Linux | Windows | その他



</body>

</html>

**Comment by ta-matsuo** [comment]
Playbook素材、対話ファイル素材、ロールパッケージ管理に以下の項目を追加する。
・「ターゲット/Linux」・・・True/Falseのプルダウン入力
・「ターゲット/Linux」・・・True/Falseのプルダウン入力
・「ターゲット/Linux」・・・シングルテキスト
・「Python要否」・・・True/Falseのプルダウン入力（対話ファイル素材には不要）

![image](https://github.com/exastro-suite/exastro-it-automation/assets/49501825/45852074-af49-460d-911d-4b101757ad4d)

**Comment by yoshi-kooooh** [comment]
True/Falseじゃなくて、＊/nullのやつでいいような気がしますね。

**Comment by ta-matsuo** [comment]
Playbook素材、対話ファイル素材、ロールパッケージ管理に以下の項目も追加する。
「Python要否」の後ろ。
・「説明」・・・マルチテキスト
・「説明(en)」・・・マルチテキスト
