### ISSUE TITLE
【Ansible】吹き出し文言の不備対応

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#213]
Ansible-LegacyRole>Movement一覧
Ansible.cfgの項目名のA大文字、吹き出しはansible.cfgのaが小文字
1系は項目名も吹き出しもansible.cfgなので小文字に併せてほしい。
（VirtualenvのVも大文字と小文字が混在している）

**Comment by ta-matsuo** [comment]
#217  でマージ済み。
