### ISSUE TITLE
【OASE】エージェント・ルールメニュー内TTLの下限値、デフォルト値を設定したい

### ISSUE THREAD

**Issue by tomoka-abe** [exastro-suite/exastro-it-automation#2131]
現在TTLの下限値が1であるためTTL1秒からでも設定できてしまうが、使い方としてふさわしくない。
また、ユーザーが設定値に困らないようにデフォルト値を追加したい。

OASE管理→エージェント、OASE→ルール
・TTLに設定できる下限値を10に変更（10秒）
・デフォルト値3600（１時間）を追加

**Comment by t-uekawa-n** [comment]
migrationを考慮
