### ISSUE TITLE
【OASE】URLという表記が分かりづらい

### ISSUE THREAD

**Issue by tomoka-abe** [exastro-suite/exastro-it-automation#2132]
OASE管理→エージェント：URLという項目が実際にはホストもしくはIPアドレスを入れるところが、URLとなっており分かりづらい。

修正箇所
・カラム名は「接続先」にする
・メールとAPIを考慮して、説明に記載する
メール‥example.com
API‥http://example.com/aaa/

**Comment by t-uekawa-n** [comment]
説明のところ、下記でお願いします

[最大長]1024バイト
接続先を入力します。

以下のように入力してください。
メールサーバの場合
　　　　→ ホスト名を入力。ex.  example.com
APIの場合
　　　   →URLを入力。ex.  http://example.com/dir/

**Comment by t-uekawa-n** [comment]
mirgrationを考慮
