### ISSUE TITLE
【OASE】ルールラベル名をグレーアウトするようにしてほしい。

### ISSUE THREAD

**Issue by kazuya-domon** [exastro-suite/exastro-it-automation#2147]
### 現状

編集を押すとルールラベル名も変更できるように見える
※実際は変更はできない。

### 理想

編集を押すとグレーアウトして変更等できないようにしてほしい。

**Comment by a-koizumi** [comment]
バリデーションエラーでチェックしているので今回は対応してない。
※吹き出しコメントを以下issueで対応
https://github.com/exastro-suite/exastro-it-automation/issues/2130
