### ISSUE TITLE
「パラメータ集」の画面自体が開かずシステムエラーとなるケースがある

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/exastro-it-automation#2156]
Aワークスペース→Bワークスペースに「パラメータ集」をエクスポート/インポートすることで顕在化するバグではなかろうか。
Aワークスペースの「パラメータ集」にて、プリセット登録をしていました。
それが邪魔をしてなのか、Bワークスペースでは、「パラメータ集」の画面をオープンすることすらできなくなってしまいました。
ユーザ側からは解決手段もなく、クリティカルな問題に思います。

**Comment by ta-matsuo** [comment]
以下の手順で発生。
①パラメータシート作成でパラメータシートを作成。
②「メニュー管理」で作成したパラメータシートを廃止。
③メニューエクスポートですべてのメニューをエクスポート。
④別のワークスペースにインポート。
⑤「パラメータ集」を開こうとするとシステムエラーが発生。
