### ISSUE TITLE
多くのメニューのデフォルトを「初回フィルタ」有効にしてほしい

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/exastro-it-automation#2158]
基本的に、よっぽど性能面でクリティカルにならない限りは、多くのメニューのデフォルトを「初回フィルタ」有効にしてほしいです。
よっぽどリスキーな蓄積系のメニューは例外にして頂いても構いませんが。

本件は、「パラメータシート作成ツール」で生成したメニューにも適用してほしいです。
※現状、パラメータシート作成ツールで生成したメニューは「初回フィルタ」が無効の状態で作られてしまうので、
　まいかい有効に変更するのがけっこうな手間です。

**Comment by ta-matsuo** [comment]
#1693 と同件なのでクローズ。
