### ISSUE TITLE
バックヤード機能や画面リフレッシュの諸々のインターバルが遅すぎる

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/exastro-it-automation#2159]
恐らく、バックヤード機能は10秒、画面リフレッシュは3秒、といったポリシーである程度統一されているように見えますが、
この結果、人間の体感的にはひどく遅く感じています。
潜在的なファンを失うよりは、ある程度サクサク動くようにする方が得策に思いますので、
バックヤード機能→3秒
画面リフレッシュ→1秒
といった格好に改めてチューニングした状態をデフォルトとしてほしいです。

※ぶっちゃけ、見せる人、見せる人、ほぼみなさんが「遅いね！」って言います。
※自動化の方が遅いのでは？など揶揄されたこともあります。。。

**Comment by t-uekawa-n** [comment]
実行系のバックヤードのINTERVALは3s
実行系の画面リフレッシュは1s

**Comment by ta-matsuo** [comment]
INTERVALを10→3に変更するコンテナは以下。
・ita-by-ansible-execute
・ita-by-conductor-synchronize
・ita-by-terraform-cli-execute
・ita-by-terraform-cloud-ep-execute
