### ISSUE TITLE
「パラメータ集」のPDF表示で幅が切れてみえるので活用が困難

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/exastro-it-automation#2161]
「パラメータ集」のPDF表示機能は大変有効な機能に思いますが、横幅がすぐに超えてしまい、表示されず、せっかくの機能なのに、事実上は活用が困難に思います。
パっと解決手段を思いつけないのですが、課題かと思います・・・

**Comment by kazuya-domon** [comment]
途切れないよう、全部表示させる方法を記載する。
