### ISSUE TITLE
【OASE】選択できるラベルのリストの最適化

### ISSUE THREAD

**Issue by t-uekawa-n** [exastro-suite/exastro-it-automation#2225]
### 機能要望の背景(任意)
OASEの機能の中で
ラベルの選択が
・ラベル付与
・フィルターのフィルター条件
・ルールの結論ラベル設定
で可能だが、_exastroの固定ラベルが
「ルールの結論ラベル設定」で設定できるのは不自然。

### 改善案・要望する機能
ルールの結論ラベル設定
で選択できるのは、ユーザ設定したラベルのみとする

**Comment by t-uekawa-n** [comment]
https://github.com/exastro-suite/exastro-it-automation/issues/2270
の中で必要になったので実施

**Comment by kazuya-domon** [comment]
■フィルター
_exastro_event_collection_settings_id
_exastro_fetched_time
_exastro_end_time
_exastro_type

■結論ラベル
_exastro_host
