### ISSUE TITLE
【メニュー作成】正規表現を設定したパラメータシートを半角英数字の値で登録作成するとバリデーションエラーになる。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#233]
【手順】
①文字列(複数行)カラムに正規表現「/^[0-9a-zA-Z]*$/」を設定する。
②パラメータシートを作成する。（半角英数字で値を登録）
　　⇒バリデーションエラーになる。

**Comment by HibikiNanri** [comment]
ITA2.0では正規表現の左右の「/(デリミタ)」はpythonの仕様のため不要となります。
「^[0-9a-zA-Z]*$」と設定する必要があります。
