### ISSUE TITLE
代入値自動登録設定に想定外のデータが保持されるため、変数刈り取りに失敗する

### ISSUE THREAD

**Issue by yoshiyuki-konuma** [exastro-suite/exastro-it-automation#2352]
### バグの説明
代入値自動登録設定のパラメータシート側代入順序のクリアタイミングが無いため、
代入値自動登録設定のレコードを登録した後にパラメータシート作成でバンドルのon/offを変更すると
バンドルoffかつ代入順序ありの状態となり、バックヤードでエラーが発生してしまう（ユーザは気づけない）

### 再現方法
1. パラメータシートをバンドルありで作成する
2. 代入値自動登録設定でパラメータシート(From)の代入順序を入れたレコードを登録する
3. パラメータシート作成で１．で作成したパラメータシートを初期化してバンドルなしで再作成する

### 本来期待する挙動
パラメータシートを初期化しバンドル無しとする時点で、Validationを入れる
　→代入値自動登録設定に代入順序が２以上のものが存在すればErrorとする
　　１のものしかなければ、その代入順序のみを削除したデータに変更する

### スクリーンショット
なし

### 動作環境
 - Exastro システムのバージョン → 2.3

**Comment by k-tomita1** [comment]
以下の内容で修正。
代入値自動登録設定に代入順序があって、パラメータシート側がバンドルでない場合、
代入値自動登録設定に代入順序がなくて、パラメータシート側がバンドルの場合、
どちらも、代入値自動登録の該当レコードを無視して、次のレコードへ進む。
