### ISSUE TITLE
【OASE】「エージェント不使用」時 リクエストメソッドは何でも入り登録可能となる。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#2433]
【機能要望】
「エージェント不使用」時 リクエストメソッドは何でも入り登録可能となるので
意味をなさない。

【改善案・要望する機能】
条件によりバリテーションチェックではじいてほしい。

**Comment by a-koizumi** [comment]
以下のissueでの要望となる。
https://github.com/exastro-suite/internal-exastro-it-automation-issue/issues/23

**Comment by t-uekawa-n** [comment]
「エージェント不使用」はある種、有効・無効のように使うことができ、先んじて登録するが使わない、やテスト的に登録してすぐに停止する、ということが可能なので、一旦、ユーザからの反応があるまでは対応は見送ります。
