### ISSUE TITLE
(ITAv2.3.0) ロール実行時に「'ansible_system' is undefinedエラーが発生する

### ISSUE THREAD

**Issue by kojitakatera** [exastro-suite/exastro-it-automation#2435]
### バグの説明
VHD仮想マシン上に構築したシステムで利用するITAv2についてv2.2.1からv2.3.0に乗り換えした後、環境によって頻度は
異なりますが、ある程度の確率で下記エラーによりAnsibleの実行がエラーになる現象を確認しています。

- TASK [/storage/org01/w03/driver/ansible/legacy_role/4e9130cf-21bd-4558-b623-fea77489a54a/in/roles/gathering :include_tasks]***
fatal: [--------]: FAILED! => { "msg": "'ansible_system' is undefined. 'ansible_system' is undefined"}

### 追加の項目
本事象について、環境毎の発生頻度やスペックをまとめました。
また、エラー発生時に採取したInput/Resultログを別途Teamsでご連絡いたしますので
お忙しいところ恐れ入りますが、ご確認いただけますと幸いです。
＃こちらで確認した感触では、ホストマシンのスペックに依存しているように見えます。

**Comment by t-uekawa-n** [comment]
movement一覧のヘッダーセクションで
  gather_facts: yes
にすることでansible_systemが収集可能になります。

https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html
