### ISSUE TITLE
(ITAv2.2.1) WIN_DirectorySetting収集結果が登録できない件について

### ISSUE THREAD

**Issue by kojitakatera** [exastro-suite/exastro-it-automation#2437]
### バグの説明
Windows2022_収集 ディレクトリの設定というMovementを実行後、
作業管理画面で収集状況のステータスと収集ログが空のままとなり、設定済みの収集項目値管理も登録されません。
下記の処理でAccessToStringというパラメータに「\n」を含んでいることが原因かと推測しておりますが、
JSON型に変更しても収集結果が登録できていない状態です。(該当する処理については、別途Teamsでご連絡させていただきます)
☆ITAv1では同じデータについて全く問題なく登録できておりました。

### 追加の項目
別途Teamsで、Windows2022_収集 ディレクトリの設定のインポート用kymファイルと
収集結果、JSON型に変更後の収集結果を添付させていただきますので、ご確認いただけますと幸いです。

**Comment by y-yonekura** [comment]
本事象について、開発環境のログに同一のメッセージがでること確認できました。
2.5にて対応予定となります。

**Comment by t-uekawa-n** [comment]
2.4.1にも修正済み
