### ISSUE TITLE
【ログイン】ログイン後に予期せぬエラーが発生

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#2440]
【バグの説明】
以下のような画面に飛ばされた。

申し訳ございません
アイデンティティー・プロバイダーへの認証リクエストを処理する際に予期せぬエラーが発生しました。

【再現方法】
直前にしていた操作は以下です。
イベントフロー画面確認中に、ログイン画面に遷移。
ログイン後に画像のような表示発生。

**Comment by a-koizumi** [comment]
以下のissueでの事象となる。
https://github.com/exastro-suite/internal-exastro-it-automation-issue/issues/64

**Comment by a-koizumi** [comment]
対応時にログは別途展開する。

**Comment by t-uekawa-n** [comment]
しばらく再現しないので、一旦クローズ
