### ISSUE TITLE
「エージェント」メニューのレスポンスリストフラグが何選んでもTrueで登録される

### ISSUE THREAD

**Issue by kazuya-domon** [exastro-suite/exastro-it-automation#2454]
### バグの説明
レスポンスリストフラグ項目をfalseにしても、画面ではtrueとなっている

### 再現方法

1. OASE管理 ＞ エージェントに移動
2. レスポンスリストフラグをFalseにして登録
3. 登録完了するが、レスポンスリストフラグをTrueになっている

### 本来期待する挙動
レスポンスリストフラグが登録時に選択したものになっていること

**Comment by tomoka-abe** [comment]
上記は接続方式を「IMAP パスワード認証」選択した際とのこと（確認済み）で、
IMAP パスワード認証の際はレスポンスリストフラグをどれにしても（選択しない/True/False）、登録・編集時にTrueになるように処理されているため、仕様通りです。
（IMAP パスワード認証の際は必ずレスポンスがリスト形式でくるため）
