### ISSUE TITLE
【OASE】ルール＞アクションの吹き出しコメントを機器一覧とかではなく、[元データ]Ansible共通/機器一覧にしてほしい。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#2455]
OASE以外のメニューグループのメニューなのでメニューグループまでの記載が望ましい。

**Comment by a-koizumi** [comment]
以下で修正お願いします。

【イベント履歴】

　イベント収集設定ID
　　　[元データ]OASE管理/エージェント/イベント収集設定ID

　評価ルール名
　　　[元データ]OASE/ルール/ルールラベル名
　　　※こちらの修正は→を/に修正してください。

【アクション】
　
　Conductor名称
　　　[元データ]Conductor/Conductor一覧/Conductor名称

　オペレーション名
　　　[元データ]基本コンソール/オペレーション一覧/オペレーション名
　
　ホスト（指定）
　　　[元データ]Ansible共通/機器一覧/ホスト名

　利用パラメータシート
　　　[元データ]パラメータシート(入力用)/パラメータシート名(ja)

　利用パラメータシート(rest)
　　　[元データ]パラメータシート(入力用)/パラメータシート名(rest)

【ルール】
　
　条件フィルターA
　　　[元データ]OASE/ルール/フィルター/フィルタID

　条件フィルターB
　　　[元データ]OASE/ルール/フィルター/フィルタID

　アクション(アクションID)
　　　[元データ]OASE/アクション/アクションID

【評価結果】
　
　ルールID
　　　[元データ]OASE/ルール/ルールID

　ルール名
　　　[元データ]OASE/ルール/ルール名

　アクションID
　　　[元データ]OASE/アクション/アクションID

　アクション名
　　　[元データ]OASE/アクション/アクション名

　ConductorインスタンスID
　　　[元データ]Conductor/Conductor作業一覧/ConductorインスタンスID

　Conductor名称
　　[元データ]Conductor/Conductor作業一覧/Conductor名称

　オペレーション(オペレーションID)
　　　[元データ]基本コンソール/オペレーション一覧/オペレーションID

　オペレーション(オペレーション名)
　　　[元データ]基本コンソール/オペレーション一覧/オペレーション名

　ホスト指定（指定ホストID）
　　　[元データ]Ansible共通/機器一覧/ホスト名

　ホスト指定（指定ホスト名）
　　　[元データ]Ansible共通/機器一覧/管理システム項番

　利用パラメータシート名
　　　[元データ]パラメータシート定義一覧/パラメータシート名(ja)

　利用パラメータシート(rest)
　　　[元データ]パラメータシート定義一覧/パラメータシート名(rest)

**Comment by tomoka-abe** [comment]
ルールメニュー内アクション/アクションIDで参照しているのはアクションIDではなくアクション名のため下記の修正追加
項目名：
アクション/アクションID→アクション/アクション名
Action/Action ID→Action/Action Name
