### ISSUE TITLE
【OASE】ルール＞評価結果の吹き出しコメントの内容がわかりづらいので見直してほしい。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#2458]
ホストIDとホスト名とか…

**Comment by kazuya-domon** [comment]
全体的に下記のようにしてほしい。
[元データ]メニューグループ:メニュー名：項目名

**Comment by a-koizumi** [comment]
https://github.com/exastro-suite/exastro-it-automation/issues/2455
の修正内容で対応してください。
