### ISSUE TITLE
【Ansible】MovementをRESTで直接更新する際に、orchestratorの値をAnsible Legacy Roleの様に文字列にしているとシステムエラーとなる。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#247]
MovementをRESTで直接更新する際に、orchestratorの値をAnsible Legacy Roleの様に文字列にしているとシステムエラーが発生し更新ができない。
新規登録の際には上記のようにしていても登録はできる。
更新時も名前で指定できるようにしてほしい。

**Comment by ta-matsuo** [comment]
issue#153 と同原因。pull request #223 マージ済み。
