### ISSUE TITLE
【メニュー作成】プルダウンカラムのパラメータシートで（同じ名前の項目）代入値自動登録設定を行うと、バリデーションエラーになる。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#249]
プルダウンカラムのパラメータシートでは、設定の仕方によって同じ名前の項目ができてしまう。
この際、代入値自動登録設定を行うと、バリデーションエラーになる。

**Comment by HibikiNanri** [comment]
「参照項目」で選択した「項目名」と同一の項目名は使用できない仕様とします。
