### ISSUE TITLE
【ロールベースアクセス制御】データレコードにロールを割り当てる際に権限(read/write/excute)を付与できるようにしてほしい。

### ISSUE THREAD

**Issue by shigeki-m** [exastro-suite/exastro-it-automation#25]
ユーザごとに作業実行を許可したいが、データレコードの変更はさせたくない。等があるため。

read : データレコードの閲覧
write : データレコードの変更
excute : movement,conductor等の作業実行

**Comment by ta-matsuo** [comment]
ITA2.xではデータごとのアクセス制御の機能は廃止された。
