### ISSUE TITLE
【ホストグループ管理】ホストグループで作成したパラメータシートの参照用のホスト名がID変換失敗になる

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#2501]
### バグの説明
ホストグループで作成したパラメータシートの参照用のホスト名がID変換失敗になる
（参照用のホスト名のIDが分割前のIDを見ているため）

### 再現方法
【手順】
①ホストグループ管理（ホストグループ一覧、ホストグループ親子紐付、ホスト紐付管理）の登録を行う。
②パラメートシートの登録をホストグループ「利用する」で登録する。
③②で作成したパラメータシートの登録をホストグループで行う。
④「参照用」を確認する。
　　⇒ホスト名がID変換失敗になる

### 本来期待する挙動
ホストグループ分割後のホストIDから名称を取得したものを表示する。

### 動作環境
 - Exastro システムのバージョン：ITA2.4.0
 （事象はホストグループ管理作成時のv2.1.0から起きる）

**Comment by t-uekawa-n** [comment]
### 本来期待する挙動

元々、現在、表示されているテーブルが間違っている。
代入値自動登録用メニューと同じ内容が表示される。
※ホストグループ名そのものが表示されるのではなく、ホストグループ分割後の対象ホストが表示される。
