### ISSUE TITLE
【全般】作成した特定のパラメータシートで全件ダウンロード（Excel）を行うとシステムエラーになる

### ISSUE THREAD

**Issue by katokeita** [exastro-suite/exastro-it-automation#2513]
### バグの説明
作成した特定のパラメータシートで全件ダウンロード（Excel）を行うとシステムエラーになります。
全件ダウンロード（Excel）及び新規登録Excel、履歴全件Excelも同様にシステムエラーになります。

### エラーコード
`0 : exception block
-> "/exastro/common_libs/api/util.py", line 168, in wrapper, controller_res = func(*args, **kwargs)
-> "/exastro/controllers/menu_excel_controller.py", line 57, in get_excel_filter, result_data = menu_excel.collect_excel_filter(objdbca, organization_id, workspace_id, menu, menu_record, menu_table_link_record, filter_parameter)
-> "/exastro/common_libs/common/menu_excel.py", line 1325, in collect_excel_filter, name_define_list = make_master_sheet(
-> "/exastro/common_libs/common/menu_excel.py", line 97, in make_master_sheet, sorted_value_list = dict(sorted(value.items(), key=lambda x: x[1]))
TypeError: '<' not supported between instances of 'float' and 'str'`

### 動作環境
 - 2.4.0

**Comment by t-uekawa-n** [comment]
・パラメータシート参照（必須、一意制約、単一行）のプルダウンを使った、パラメータシートを利用。
・プルダウンの登録時に、Excelインポートを使用。数値やfloatの値があり、型が「標準」
※文字列と数値が混在すると一意制約も突破する模様
※パラメータシートの値がJSON型であるために、インポート時の値そのままで維持されてしまう（文字列に変換がかからない）
→
パラメータシートのExcelインポート時に、型を揃えて保存する。

**Comment by t-uekawa-n** [comment]
> パラメータシート側のカラムの型に揃えて保存するのが良いか
APIと収集機能に影響
https://ita-docs-staging.exastro.org/ja/2.4/manuals/ansible-driver/collect.html#about-execute-example

**Comment by t-uekawa-n** [comment]
・一意制約は、実際の値の型が違っても、バリデーションチェックされるべき
・ダウンロード（Excel）も同様に、実際の値の型が違っても、ソートできてシステムエラーにならずに出力されるべき

**Comment by t-uekawa-n** [comment]
このissueでは
・一意制約は、実際の値の型が違っても、バリデーションチェックされるべき
・ダウンロード（Excel）も同様に、実際の値の型が違っても、ソートできてシステムエラーにならずに出力されるべき
を修正し
送信値の型が、パラメータシートでの定義の型と違っていても、そのまま保存されている問題は別issueで修正する

**Comment by yutoyajimaaa** [comment]
プルダウン選択項目で、値が無いデータシートを参照先にしている場合にも、同じような事象が発生する。（2.4.1）
