### ISSUE TITLE
収集結果のyamlファイルに2つのVARがある場合、収集結果が登録されない

### ISSUE THREAD

**Issue by murata-kxc** [exastro-suite/exastro-it-automation#2516]
### バグの説明
VAR_WIN_XXXが2つの収集結果のyamlファイルでは、画面上の「収集状況」の「ステータス」と「収集ログ」の欄が
空となり、収集結果が登録されない。
(VAR_WIN_XXXが1つだけの収集結果のyamlファイルでは正常に収集結果が登録できることは確認済み)

以下パタンにて試した時のyamlファイルと画面を添付します。
・VAR_WIN_XXXが1つの場合(VAR_WIN_NetAdapterConfiguration_ITA のみ)
・VAR_WIN_XXXが2つの場合(VAR_WIN_NetAdapterConfiguration_ITA と VAR_WIN_dnsSuffix_specific_ITA)
[Uploading ResultData_VARが1つの場合.zip…]()
[Uploading ResultData_VARが2つの場合.zip…]()
![Uploading VARが2つの場合に収集結果が登録されない画面.png…]()

### 動作環境
ITA v2.2.1

**Comment by t-uekawa-n** [comment]
下記のバグと原因を同じしている模様
https://github.com/exastro-suite/exastro-it-automation/issues/2437

2.5では上記対応を行った結果、正常に収集できることを確認済み
2.4.1と2.4.2で同様かを確認中
