### ISSUE TITLE
【Document】監視ソフト毎のエージェント設定例の通り設定すると同一イベントが複数取得されることがある。

### ISSUE THREAD

**Issue by kazuya-domon** [exastro-suite/exastro-it-automation#2536]
### 説明
表 2.93 Zabbixの設定例のイベントIDキーをその通りに設定すると、大量に同じイベントが取れてきた。

### 再現方法
zabbixからイベント取得するように設定

### 本来期待する挙動
自分の環境ではイベントIDキーをobjectidにしたら止まった。
再度、設定例通りにeventidにしたら今度はひとつづつ取れた。

### スクリーンショット
![image](https://github.com/user-attachments/assets/e503d7fe-81b6-4b3c-9e9c-ecbf3c1d9787)
![image](https://github.com/user-attachments/assets/86738804-ac3b-4801-bc68-3d4b4f986e2f)
![image](https://github.com/user-attachments/assets/f717af4c-dbab-4773-8d08-6f929957a416)

### 動作環境
 - OS:RHEL
　Exastro 2.4.2
 - OS：Censtos8
　zabbix5.2

### 追加
URLの部分が「ttp://～」となっています。

![image](https://github.com/user-attachments/assets/d39aeb89-bcd6-4c22-9382-9375fdff40db)

**Comment by t-uekawa-n** [comment]
`{
  "jsonrpc":"2.0",
  "method":"problem.get",
  "id":1,
  "params": {
    "time_from": "EXASTRO_LAST_FETCHED_TIMESTAMP"
},
"auth":""
}`

前回取得日時の予約変数をtime_fromにセットする
