### ISSUE TITLE
【比較機能】バンドルメニューを比較した際に、変更がないものも差分ありのチェックが入る

### ISSUE THREAD

**Issue by kazuya-domon** [exastro-suite/exastro-it-automation#2553]
### バグの説明
バンドルメニューを比較した際に、変更がないものも差分ありのチェックが入る

### 再現方法
バンドルメニューを用意して、パラメータを用意。
差分ありとなしものを用意
比較する。

### 本来期待する挙動
差分がない場合はチェックが入らないようになっていると見栄えがいい

### スクリーンショット
![image](https://github.com/user-attachments/assets/45348059-46aa-465c-a500-5db56e78293d)

**Comment by yutoyajimaaa** [comment]
下記Issueと同じ原因。対応済み。
https://github.com/exastro-suite/exastro-it-automation/issues/2634
