### ISSUE TITLE
【全般】廃止したレコードのあるパラメータシートに、あとから必須項目を追加すると廃止したレコードが復活できなくなる

### ISSUE THREAD

**Issue by katokeita** [exastro-suite/exastro-it-automation#2565]
廃止したレコードのあるパラメータシートに、あとから必須項目を追加すると廃止したレコードが復活できなくなります。

復活時、各項目に入力できるようになっているが、
入力した項目は編集反映時に無視されるため、必須項目のバリデーションエラーになってしまう。

### 改善案・要望する機能
復活時、項目に入力できないようにする。

**Comment by t-uekawa-n** [comment]
→
復活時、項目に入力できないようにする対応を行った。
