### ISSUE TITLE
Conductor一覧をエクスポート/インポートした場合インポート先に持っていくが 「詳細」ボタン押下時「読み込に失敗しました。」となる。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#2581]
**バグの説明**
![image](https://github.com/user-attachments/assets/b0c51939-adf6-4f69-b23d-73712251dc91)

![image](https://github.com/user-attachments/assets/2b399878-d02c-446f-9e29-8239ce0092dd)

**動作環境**
 - ITA-v2.5.0

**Comment by t-uekawa-n** [comment]
![image](https://github.com/user-attachments/assets/f299d883-864d-48c1-8b28-d94b0d4ba53a)
