### ISSUE TITLE
【エクスポート/インポート】ドライバ差分ありでエクスポート・インポートした際に、データが登録されないメニューがある。 

### ISSUE THREAD

**Issue by y-yonekura** [exastro-suite/exastro-it-automation#2583]
### バグの説明
ドライバ差分がある状態でエクスポート・インポートを実行すると、インポート自体は完了するが、
データ欠損のメニューが存在する。

### 再現方法
エクスポートする環境にドライバXは無し、
インポートする環境にドライバXがある場合のエクスポート・インポートを実施。

①環境A（Terraform CLI 無し）でデータ登録、エクスポート。
②環境B（全ドライバあり）へ①のKYMをインポート

インポート自体は成功するが、レコードが空で、登録されていない状態となるメニューがある

### 本来期待する挙動
インポートが完了し、エクスポートしたデータがインポートされていること。

### 動作環境
 - Exastro システムのバージョン：　2.5.0
 
### 追加の項目
以下は、回避手段で、ドライバインストール、アンインストール機能を利用して、
ドライバ環境を揃えた状態でインポート実施。
①環境A（Terraform CLI 無し）でデータ登録
②環境AにTerraform CLI インインストールして、（全ドライバあり）状態でエクスポート
③環境B（全ドライバあり）へ①のKYMをインポート

**Comment by t-uekawa-n** [comment]
#2572 と被っているので閉じる。削除しても問題ない
