### ISSUE TITLE
【パラメータシート作成】コピーした項目で「必須」「一意制約」の編集ができない

### ISSUE THREAD

**Issue by yagireina** [exastro-suite/exastro-it-automation#2586]
### バグの説明
作成したパラメータシートを編集する際に、項目をコピーして編集しようとしたところ
「必須」「一意制約」の編集ができなかった。

### 再現方法
①作成したパラメータシートの編集ボタンを押下する
![image](https://github.com/user-attachments/assets/ab3236f4-9bfb-4bb4-95f9-7715e163e115)

②項目をコピーすると編集ができない
![image](https://github.com/user-attachments/assets/f0ae5c52-69f6-4f06-8149-5bfe541d9bf2)

### 本来期待する挙動
新規追加項目だけに限らず、コピーした項目も「必須」「一意制約」の編集をできるようにしてほしい。

### 動作環境
 - Exastro v2.4.1

**Comment by t-uekawa-n** [comment]
2.4.2で修正ずみ
https://github.com/exastro-suite/exastro-it-automation/issues/2468
