### ISSUE TITLE
最新資材をビルドしたところansible-agentで エラーになる。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#2590]
### バグの説明
【事象】
以下をビルドしたところ以下ansible-agentでエラーになりました。

exastro/exastro-it-automation-by-ansible-agent:alpha.387ee8.20241025-145522
exastro/exastro-it-automation-by-ansible-agent-snow:alpha.387ee8.20241025-145522

※telnet の dnf installで失敗しているように思われる。

【ログ】
[build-and-push] #11 8.771   - Status code: 404 for http://ftp.udx.icscoe.jp/Linux/almalinux/8.10/AppStream/x86_64/os/repodata/f926ff907fd917310dc34d935b25211a5830fb0b4c5546b297b91d082565a2d9-primary.xml.gz (IP: 10.51.8.112)
[build-and-push] #11 8.771   - Status code: 404 for http://jp.mirrors.cicku.me/almalinux/8.10/AppStream/x86_64/os/repodata/2d9d52ca33f92bda51367c7da1d10c9e78b8b5beacaaf4c76e922b6de6a135bc-updateinfo.xml.gz (IP: 10.51.8.112)
[build-and-push] #11 8.771   - Status code: 404 for http://mirrors.xtom.jp/almalinux/8.10/AppStream/x86_64/os/repodata/c78a0a4c9d370d7008fd91f4162075c4277d9d7390c960926d2aaa7642032818-filelists.xml.gz (IP: 10.51.8.112)
[build-and-push] #11 8.771   - Status code: 404 for https://alma.jp.macarne.com/8.10/AppStream/x86_64/os/repodata/2d9d52ca33f92bda51367c7da1d10c9e78b8b5beacaaf4c76e922b6de6a135bc-updateinfo.xml.gz (IP: 10.51.8.112)
[build-and-push] #11 8.810 Error: Failed to download metadata for repo 'appstream': Yum repo downloading error: Downloading error(s): repodata/f926ff907fd917310dc34d935b25211a5830fb0b4c5546b297b91d082565a2d9-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/c78a0a4c9d370d7008fd91f4162075c4277d9d7390c960926d2aaa7642032818-filelists.xml.gz - Cannot download, all mirrors were already tried without success; repodata/2d9d52ca33f92bda51367c7da1d10c9e78b8b5beacaaf4c76e922b6de6a135bc-updateinfo.xml.gz - Cannot download, all mirrors were already tried without success
[build-and-push] #11 ERROR: process "/bin/sh -c dnf install -y --enablerepo=appstream telnet" did not complete successfully: exit code: 1
[build-and-push] ------
[build-and-push]  > [common_build  9/10] RUN --mount=type=secret,id=host_certificate_file,dst=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem     dnf install -y --enablerepo=appstream telnet:
[build-and-push] ------
[build-and-push] process "/bin/sh -c dnf install -y --enablerepo=appstream telnet" did not complete successfully: exit code: 1

container step-build-and-push has failed  : [{"key":"StartedAt","value":"2024-10-25T06:43:09.772Z","type":"InternalTektonResult"}]
 

### 本来期待する挙動
エラーにならず正常に終了する。

### 動作環境
 - Exastro システムのバージョン：v2.5最新

**Comment by t-uekawa-n** [comment]
再現性がないため、一旦クローズ
