### ISSUE TITLE
比較設定のメニューでID変換エラーが発生している場合、比較実行の画面を開いた時点でシステムエラーとなる

### ISSUE THREAD

**Issue by yoshiyuki-konuma** [exastro-suite/exastro-it-automation#2598]
### バグの説明
比較実行の画面を開くとシステムエラーとなる。

パラメータシートを作成しなおしたことにより、比較設定のレコードでID変換エラーが存在したためと思われる

### 再現方法
パラメータシートを作成
比較設定のレコードを作成
パラメータシートを廃止
比較実行の画面を開く

### 本来期待する挙動
比較設定のレコードで対象のパラメータシートが廃止されているなどしてID変換エラーになっていても、
比較実行画面は表示されるべき
比較実行の選択肢としては選べない状態になっているべき（選択肢として非表示）

### 動作環境
 - Exastro 2.4.1

**Comment by t-uekawa-n** [comment]
再現しないので、取り下げ
