### ISSUE TITLE
【ホストグループ】ファイルアップロード項目のみのパラメータシートが、代入値自動登録用でファイルが参照、取得できない

### ISSUE THREAD

**Issue by y-yonekura** [exastro-suite/exastro-it-automation#2624]
### バグの説明
・代入値自動登録用のパラメータシートで、ファイルを参照、DLしようとすると、空ファイルとなる。
・作業実行で代入値にファイルアップロード項目が連携されない

### 再現方法
パラメータシート作成で、以下の条件でパラメータシート作成する
・ファイルアップロード項目のみ
・ホストグループ利用

作成されたパラメータシートにデータを登録する。
代入値自動登録用のパラメータシートでファイルの参照、取得を行う。

該当パラメータシートと代入値自動登録して作業実行を行う。

### 本来期待する挙動
代入値自動登録用のパラメータシートでファイルの参照、取得で問題ないこと
作業実行で、ファイルアップロード項目が連携できていること

### 動作環境
 - Exastro システムのバージョン：　2.5.0、 2.5.1

### 暫定対応
ファイルアップロード項目のみのメニューにしないこと
対象：ホストグループ利用で、ファイルアップロード項目のみのパラメータシート
対応：
　①パラメータシート定義一覧→該当のパラメータシートの「パラメータシート定義・作成」を押下
　②編集→項目追加（単一行）等を追加
　③作成（編集）

**Comment by t-uekawa-n** [comment]
https://github.com/exastro-suite/exastro-it-automation/issues/2501
の考慮もれ
