### ISSUE TITLE
【比較機能】画面上でnullと空文字の差分の内容が分からない

### ISSUE THREAD

**Issue by yutoyajimaaa** [exastro-suite/exastro-it-automation#2627]
### バグの説明
文字列カラムの比較で、nullと空文字が入ったパラメーターシートの比較を行うと、画面上で「差分あり」と表示されるが、差分の内容が表示されない。

### 本来期待する挙動
何かしらの方法でnullと空文字が入っていることが分かるようになる
例：マウスカーソル合わせると「””とNULLで差分あり」と表示される

### スクリーンショット
![image](https://github.com/user-attachments/assets/82e7eebc-7ca6-474c-a742-be7521e81a7a)

**Comment by t-uekawa-n** [comment]
![image](https://github.com/user-attachments/assets/89c8967b-a5f8-48c0-9620-6cf079c14ca2)
