### ISSUE TITLE
【比較機能】項目名の末尾が"]"の比較で差分があっても差分なしとなる

### ISSUE THREAD

**Issue by yutoyajimaaa** [exastro-suite/exastro-it-automation#2644]
### バグの説明
項目名の最後が"]"で終わるパラメーターシート（バンドル利用のパラメーターシートは必ずおこる）の比較で、入力内容に差分があっても、正しい区比較されずに、差分なしの表示となる。

### 本来期待する挙動
差分がある場合は、差分ありの表示となる

### 動作環境
 - 2.5.1

**Comment by t-uekawa-n** [comment]
https://github.com/exastro-suite/exastro-it-automation/issues/2582
のデグレ
