### ISSUE TITLE
「パラメータシート定義・作成」にてプルダウン選択をコピーするとコピー先にて選択項目を変えようとしても変わらない

### ISSUE THREAD

**Issue by yoshi-kooooh** [exastro-suite/exastro-it-automation#2662]
### バグの説明
「パラメータシート定義・作成」にてプルダウン選択をコピーするとコピー先にて選択項目を変えようとしても変わらない
(コピー元から編集できない)

### 再現方法
・「パラメータシート定義・作成」のメニューにて、プルダウン選択の項目を作る
・その項目をコピーする
・コピー先の対して、「選択項目」を変更しようとするも、変更できない

### 本来期待する挙動
コピー先にて選択項目を変えようとすれば変えられる

**Comment by t-uekawa-n** [comment]
@yoshi-kooooh 
こちらは
https://github.com/exastro-suite/exastro-it-automation/issues/2467
v2.4.2およびv2.5で対応済みとなります。
よろしくお願いします。
