### ISSUE TITLE
Movement数が多くなるとConductor作業確認に配置されているMovementが小さくなり、視認性が悪くなるため改善してほしい

### ISSUE THREAD

**Issue by y-masaya3210** [exastro-suite/exastro-it-automation#27]
Movementのサイズも統一感が無くグリッドされるわけではないため、視認性が悪くなっている。何かしら改善をしてほしい。

**Comment by katokeita** [comment]
下記の機能を追加しました。
・ノード移動時に升目に吸着（グリッドにスナップ）
・キャンバス縮小時にホバーしたノードを原寸で表示
・Movement一括サイズ指定
