### ISSUE TITLE
【機能要望】表示フィルタの項目を任意に設定できる機能が欲しい

### ISSUE THREAD

**Issue by y-oka2** [exastro-suite/exastro-it-automation#323]
以下のような機能が欲しい。
・不要カラムの削除機能(Noや更新者情報等)
・カラムの表示領域を変更できる機能

**Comment by sinatommy** [comment]
[カラムの表示領域を変更できる機能がほしい](https://github.com/exastro-suite/exastro-it-automation/issues/552)は別issueへ
