### ISSUE TITLE
ログレベルの制御

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/exastro-it-automation#350]

**Comment by ta-matsuo** [comment]
コンテナごとにログレベルを設定できるようにする。
⇒adminのRestAPIでログレベルの参照、設定をする
⇒ita_dbにログレベルを保持するテーブルを追加する

自分がなんのコンテナなのかは、DockerfileにENVでコンテ名を追加する
⇒ログ出力の中でg.LOG_LEVELを確認
　⇒はいってなければ、ログレベルのテーブルみてログレベルを取得＋g.LOG_LEVELに設定
　⇒はいっていれば、g.LOG_LEVELに従う

バックヤードログは、正常時はINFOは何も出力されないようにしたい
DEBUGはOK

adminやorganizationのログの精査
