### ISSUE TITLE
【全般】Webログの詳細化

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/exastro-it-automation#38]
(ITAインストールディレクトリ)/ita-root/logs/webaplogs
のログ出力内容を詳細化する。
ログレベルを設けて、問題発生時の調査に対応できるようにする。

**Comment by ta-matsuo** [comment]
ITA2.xでは、ログレベルをDEBUG、INFO、ERRORに分けておりログレベルを変更できる機能を具備した。
