### ISSUE TITLE
代入値管理の登録と追加の仕様について

### ISSUE THREAD

**Issue by y-masaya3210** [exastro-suite/exastro-it-automation#42]
代入値管理のレコード数が膨大のため、パラメータシートに追加の登録を行った際に、上限メモリを超えてエラーとなってしまった。メモリの上限を上げることでエラーが解消され、代入値登録の仕様を確認をしたところテーブル全件が1度にメモリが乗る仕様になることが原因と思われるため、代入値管理のレコード数に左右されない仕様に改善することはできないでしょうか。

**Comment by ta-matsuo** [comment]
ITA1.xでは代入値自動登録を元に代入値管理の登録・更新をする処理が随時行われていたが、
ITA2.xでは作業実行時にのみ代入値自動登録を元に代入値管理に登録する処理に変更になった。
作業に必要な代入値管理の登録のみ行うため、代入値管理全体を読み込む処理は無くなった。
