### ISSUE TITLE
【全般】最終更新日時に文字入力しフィルターかけると「システムエラー」になる。

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#509]
![image](https://user-images.githubusercontent.com/49502759/207189259-3ab2ca1f-cf79-4604-bab2-42904052456e.png)

**Comment by ta-matsuo** [comment]
DBがMySQLの場合、日付型のカラムと日付形式でない値をSQLで比較した際にエラーになる。
MariaDBの場合はエラーにならない。
エラーを回避するために、フィルタで指定された値が日付形式であるかどうか確認する処理を追加する。
