### ISSUE TITLE
[機能要望]バックヤードに出力されたエラーをITA上に出してほしい

### ISSUE THREAD

**Issue by yagireina** [exastro-suite/exastro-it-automation#539]
例：SQLの実行失敗エラー(カラム数等が上限に達したことによるエラー)
上記のような場合、バックヤードログを確認しないと、エラーの原因を切り分けることができないため
原因を特定するのに時間がかかる。
ITA上にバックヤードのエラーを表示させ確認できるようにしてほしい。

**Comment by sinatommy** [comment]
[画面からログの確認 or 出力 or ログ収集できるようにする](https://github.com/exastro-suite/exastro-it-automation/issues/115)にマージ
