### ISSUE TITLE
【メニュー作成】「入力方式：パラメータシート参照」の追加

### ISSUE THREAD

**Issue by a-koizumi** [exastro-suite/exastro-it-automation#757]
Terraform機能の追加に基づいて以下、メニュー作成の入力方式を追加する。

入力方式：パラメータシート参照
(作成対象「パラメータシート(オペレーションあり)」で作成したメニューをプルダウンから選択します。)

関連issue
#346 
#347

**Comment by HibikiNanri** [comment]
縦メニューの場合は、Operationの値が一意にならないため対象外とする。
