### ISSUE TITLE
「Ansible 共通 > テンプレート管理」の説明が不正確

### ISSUE THREAD

**Issue by wreathvine** [exastro-suite/exastro-it-automation#808]
## 概要

`Ansible 共通 > テンプレート管理` の説明が、「VAR_」をつけなくても使えるので、正確でない。

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/83527822/223368951-93d6e64b-d5fe-448d-88dc-36abe6c76e2d.png)

**Comment by sinatommy** [comment]
2系からは、変数はVAR_を付けなくても変数として認識できるようになっている。｛｛｝｝で囲まれたものを変数として認識する。
