### ISSUE TITLE
【メニュー作成】メニュー定義一覧の編集ボタンより、メニュー名(REST)がメニュー作成状態が「作成済み」であっても変更可能

### ISSUE THREAD

**Issue by kamakura-m** [exastro-suite/exastro-it-automation#816]
メニュー作成状態が「作成済み」であっても、メニュー名(REST)がメニュー定義一覧の編集ボタンからだと更新可能。

①メニュー定義一覧→メニュー定義・作成　からだと編集・初期化ボタン押下後の双方の場合でメニュー名(REST)の編集が不可

![image](https://user-images.githubusercontent.com/103919073/223889344-aeb87b72-3e4a-40a6-8a95-5288a7d2250e.png)

②メニュー定義一覧→編集ボタン　からだとメニュー名(REST)の編集ができ、更新可能（メニュー作成状態：作成済みでも）

![image](https://user-images.githubusercontent.com/103919073/223887840-6c95db2a-8c21-410e-a6aa-5b1e0449f0c6.png)

**Comment by HibikiNanri** [comment]
「作成対象」「縦メニュー利用」などの「編集」で変更できない項目を「メニュー定義一覧」メニューから変更して「編集」を実行した際には、不整合が起こる可能性がある。
上記についてはマニュアルに記載する。
