### ISSUE TITLE
【Ansible】【Terraform】変数ネスト管理の「最大繰り返し数」の上限値をユーザ可変にする

### ISSUE THREAD

**Issue by sinatommy** [exastro-suite/exastro-it-automation#876]
上限値1024を、ユーザが変更できるようにする。[【Ansible】【Terraform】変数ネスト管理の「最大繰り返し数」の上限値見直し #788](https://github.com/exastro-suite/exastro-it-automation/issues/788)

**Comment by tomoka-abe** [comment]
・上限値の設定は「システム管理」メニューで値を設定可能にする
・上限値のMAXの値は1024で固定し、ユーザー可変の値は1024以下にする
